# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(577, 483)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sort_input = QtWidgets.QLineEdit(Form)
        self.sort_input.setObjectName("sort_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sort_input)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.roasting_input = QtWidgets.QComboBox(Form)
        self.roasting_input.setObjectName("roasting_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roasting_input)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.grain_input = QtWidgets.QComboBox(Form)
        self.grain_input.setObjectName("grain_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.grain_input)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.description_input = QtWidgets.QTextEdit(Form)
        self.description_input.setObjectName("description_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.description_input)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.price_input = QtWidgets.QLineEdit(Form)
        self.price_input.setObjectName("price_input")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.price_input)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.volume_input = QtWidgets.QLineEdit(Form)
        self.volume_input.setObjectName("volume_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.volume_input)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Сорт"))
        self.label_2.setText(_translate("Form", "Обжарка"))
        self.label_3.setText(_translate("Form", "Молотый / в зёрнах"))
        self.label_4.setText(_translate("Form", "Описание"))
        self.label_5.setText(_translate("Form", "Цена"))
        self.label_6.setText(_translate("Form", "Объём упаковки"))
        self.pushButton.setText(_translate("Form", "Сохранить"))
